#ifndef WEB_PAGE_H
#define WEB_PAGE_H

static const char PAGE_HTML[] =
"<!DOCTYPE html>"
"<html lang='zh'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>\xe6\x9c\xba\xe6\xa2\xb0\xe8\x87\x82\xe6\x8e\xa7\xe5\x88\xb6</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:system-ui,-apple-system,sans-serif;background:#1a1a2e;color:#e0e0e0;padding:12px;max-width:600px;margin:0 auto}"
"h1{text-align:center;font-size:1.3em;padding:10px 0;border-bottom:2px solid #16213e}"
"#mode-bar{text-align:center;padding:8px;margin:8px 0;border-radius:6px;font-weight:bold;font-size:1.1em}"
".m-idle{background:#333}.m-web{background:#0f3460}.m-teach{background:#1a5d1a}.m-play{background:#8b4513}.m-imu{background:#8B008B}"
".joint{margin:8px 0;padding:10px;background:#16213e;border-radius:8px}"
".joint label{display:flex;justify-content:space-between;font-size:0.9em;margin-bottom:4px}"
".joint input[type=range]{width:100%;height:24px;cursor:pointer;accent-color:#e94560}"
".joint input[type=range]:disabled{opacity:0.4;cursor:not-allowed}"
".val{font-weight:bold;color:#e94560;min-width:40px;text-align:right}"
".speed-box{margin:8px 0;padding:10px;background:#16213e;border-radius:8px}"
".speed-box label{display:flex;justify-content:space-between;font-size:0.9em;margin-bottom:4px}"
".speed-box input[type=range]{width:100%;height:24px;cursor:pointer;accent-color:#ffa500}"
".speed-val{font-weight:bold;color:#ffa500}"
".btns{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px;margin:10px 0}"
".btns button{padding:12px 4px;border:none;border-radius:6px;font-size:0.9em;font-weight:bold;cursor:pointer;color:#fff;transition:opacity 0.2s}"
".btns button:active{opacity:0.7}"
".btns button:disabled{opacity:0.3;cursor:not-allowed}"
"#btn-web{background:#0f3460}#btn-teach{background:#1a5d1a}#btn-stop{background:#c23616}"
"#btn-play{background:#8b4513}#btn-loop{background:#6a3093}#btn-home{background:#444}"
"#btn-imu{background:#8B008B}"
"#imu-bar{text-align:center;font-size:0.85em;padding:4px;color:#aaa}"
"#imu-bar .on{color:#0f0}#imu-bar .off{color:#f00}"
"#ee-bar{text-align:center;font-size:0.85em;padding:4px;color:#aaa}"
"#status{font-size:0.8em;color:#888;text-align:center;padding:6px;margin-top:8px}"
"#status span{margin:0 8px}"
"#rec-bar{text-align:center;font-size:0.85em;padding:4px;color:#aaa}"
"</style>"
"</head>"
"<body>"
"<h1>\xe6\x9c\xba\xe6\xa2\xb0\xe8\x87\x82\xe6\x8e\xa7\xe5\x88\xb6\xe5\x99\xa8</h1>"
"<div id='mode-bar' class='m-idle'>\xe7\xa9\xba\xe9\x97\xb2</div>"
"<div id='joints'></div>"
"<div class='speed-box'>"
"<label><span>\xe8\xbf\x90\xe5\x8a\xa8\xe9\x80\x9f\xe5\xba\xa6</span><span class='speed-val' id='spd-v'>500</span></label>"
"<input type='range' id='spd-s' min='50' max='2000' value='500'>"
"</div>"
"<div id='rec-bar'>\xe5\xbd\x95\xe5\x88\xb6: <span id='rec-n'>0</span>/6000</div>"
"<div class='btns'>"
"<button id='btn-web' onclick='sendCmd(\"web_control\")'>\xe6\x89\x8b\xe5\x8a\xa8\xe6\x8e\xa7\xe5\x88\xb6</button>"
"<button id='btn-teach' onclick='sendCmd(\"teach_start\")'>\xe7\xa4\xba\xe6\x95\x99</button>"
"<button id='btn-stop' onclick='sendCmd(\"stop\")'>\xe5\x81\x9c\xe6\xad\xa2</button>"
"<button id='btn-play' onclick='doPlay(false)'>\xe6\x92\xad\xe6\x94\xbe</button>"
"<button id='btn-loop' onclick='doPlay(true)'>\xe5\xbe\xaa\xe7\x8e\xaf\xe6\x92\xad\xe6\x94\xbe</button>"
"<button id='btn-home' onclick='goHome()'>\xe5\x9b\x9e\xe5\x8e\x9f\xe7\x82\xb9</button>"
"<button id='btn-imu' onclick='sendCmd(\"imu_control\")'>IMU \xe9\x81\xa5\xe6\x8e\xa7</button>"
"</div>"
"<div id='imu-bar'>IMU: <span id='imu-st' class='off'>\xe6\x9c\xaa\xe8\xbf\x9e\xe6\x8e\xa5</span></div>"
"<div id='ee-bar' style='display:none'>\xe6\x9c\xab\xe7\xab\xaf: X=<span id='ee-x'>0</span> Y=<span id='ee-y'>0</span> Z=<span id='ee-z'>0</span> mm</div>"
"<div class='speed-box' id='sens-box'>"
"<label><span>IMU \xe7\x81\xb5\xe6\x95\x8f\xe5\xba\xa6</span><span class='speed-val' id='sens-v'>2.0</span></label>"
"<input type='range' id='sens-s' min='5' max='50' value='20'>"
"</div>"
"<div id='status'>"
"<span id='ws-st'>\xe8\xbf\x9e\xe6\x8e\xa5: --</span>"
"<span id='ip-st'>IP: --</span>"
"</div>"
"<script>"
"var ws,mode='idle',sendTimer=null,spdVal=500;"
"var JC=["
"{id:1,name:'J1 \xe5\xba\x95\xe5\xba\xa7',min:1900,max:4000,home:3000},"
"{id:2,name:'J2 \xe8\x82\xa9\xe9\x83\xa8',min:1000,max:2500,home:2180},"
"{id:3,name:'J3 \xe8\x82\x98\xe9\x83\xa8',min:1550,max:3000,home:1550},"
"{id:4,name:'J4 \xe8\x85\x95\xe9\x83\xa8',min:400,max:4000,home:1970},"
"{id:5,name:'J5 \xe6\x89\x8b\xe8\x85\x95',min:2200,max:4000,home:3000},"
"{id:6,name:'J6 \xe5\xa4\xb9\xe7\x88\xaa',min:2000,max:4000,home:2048}"
"];"
"var vals=[3000,2180,1550,1970,3000,2048];"
"function init(){"
"var c=document.getElementById('joints');"
"JC.forEach(function(j,i){"
"var d=document.createElement('div');d.className='joint';"
"d.innerHTML='<label><span>'+j.name+'</span><span class=\"val\" id=\"v'+i+'\">'+j.home+'</span></label>'"
"+'<input type=\"range\" id=\"s'+i+'\" min=\"'+j.min+'\" max=\"'+j.max+'\" value=\"'+j.home+'\">';"
"c.appendChild(d);"
"var sl=d.querySelector('input');"
"sl.oninput=function(){vals[i]=parseInt(this.value);document.getElementById('v'+i).textContent=this.value;throttleSend();};"
"});"
"document.getElementById('spd-s').oninput=function(){"
"spdVal=parseInt(this.value);document.getElementById('spd-v').textContent=spdVal;"
"if(ws&&ws.readyState===1)ws.send(JSON.stringify({cmd:'speed',v:spdVal}));};"
"document.getElementById('sens-s').oninput=function(){"
"var sv=parseInt(this.value)/10.0;document.getElementById('sens-v').textContent=sv.toFixed(1);"
"if(ws&&ws.readyState===1)ws.send(JSON.stringify({cmd:'imu_sensitivity',v:sv}));};"
"connect();"
"}"
"function connect(){"
"var h=location.host||location.hostname+':80';"
"ws=new WebSocket('ws://'+h+'/ws');"
"ws.onopen=function(){document.getElementById('ws-st').textContent='\xe8\xbf\x9e\xe6\x8e\xa5: \xe6\xad\xa3\xe5\xb8\xb8';document.getElementById('ip-st').textContent='IP: '+location.hostname;};"
"ws.onclose=function(){document.getElementById('ws-st').textContent='\xe8\xbf\x9e\xe6\x8e\xa5: \xe6\x96\xad\xe5\xbc\x80';setTimeout(connect,3000);};"
"ws.onmessage=function(e){"
"try{var d=JSON.parse(e.data);}catch(x){return;}"
"if(d.st==='pos'){"
"d.j.forEach(function(p,i){document.getElementById('v'+i).textContent=p;"
"if(mode!=='web_control'){document.getElementById('s'+i).value=p;vals[i]=p;}});"
"if(d.m&&d.m!==mode){var oldM=mode;mode=d.m;if(mode==='web_control'){d.j.forEach(function(p,i){document.getElementById('s'+i).value=p;vals[i]=p;});}updateUI();}"
"if(d.n!==undefined)document.getElementById('rec-n').textContent=d.n;"
"if(d.imu!==undefined){var ist=document.getElementById('imu-st');ist.textContent=d.imu?'\xe5\xb7\xb2\xe8\xbf\x9e\xe6\x8e\xa5':'\xe6\x9c\xaa\xe8\xbf\x9e\xe6\x8e\xa5';ist.className=d.imu?'on':'off';}"
"if(d.ee){document.getElementById('ee-bar').style.display='';document.getElementById('ee-x').textContent=d.ee[0].toFixed(1);document.getElementById('ee-y').textContent=d.ee[1].toFixed(1);document.getElementById('ee-z').textContent=d.ee[2].toFixed(1);}else{document.getElementById('ee-bar').style.display='none';}"
"}"
"if(d.st==='mode'){mode=d.m;updateUI();}"
"if(d.st==='play'){document.getElementById('rec-n').textContent=d.i+'/'+d.n;}"
"if(d.st==='error'){alert(d.msg);}"
"};"
"}"
"function sendCmd(c){if(ws&&ws.readyState===1)ws.send(JSON.stringify({cmd:c}));}"
"function goHome(){sendCmd('home');var homes=[3000,2180,1550,1970,3000,2048];homes.forEach(function(h,i){vals[i]=h;document.getElementById('s'+i).value=h;document.getElementById('v'+i).textContent=h;});}"
"function doPlay(loop){if(ws&&ws.readyState===1)ws.send(JSON.stringify({cmd:'play',loop:loop}));}"
"function throttleSend(){if(sendTimer)return;sendTimer=setTimeout(function(){sendTimer=null;"
"if(mode==='web_control'&&ws&&ws.readyState===1)ws.send(JSON.stringify({cmd:'pos',j:vals}));},50);}"
"function updateUI(){"
"var mb=document.getElementById('mode-bar');"
"var names={idle:'\xe7\xa9\xba\xe9\x97\xb2',web_control:'\xe6\x89\x8b\xe5\x8a\xa8\xe6\x8e\xa7\xe5\x88\xb6',teaching:'\xe7\xa4\xba\xe6\x95\x99\xe4\xb8\xad',playback:'\xe6\x92\xad\xe6\x94\xbe\xe4\xb8\xad',imu_control:'IMU \xe9\x81\xa5\xe6\x8e\xa7'};"
"var cls={idle:'m-idle',web_control:'m-web',teaching:'m-teach',playback:'m-play',imu_control:'m-imu'};"
"mb.textContent=names[mode]||mode;mb.className=cls[mode]||'m-idle';"
"var isWeb=mode==='web_control';"
"for(var i=0;i<6;i++){document.getElementById('s'+i).disabled=!isWeb;}"
"}"
"init();"
"</script>"
"</body>"
"</html>";

#endif
